_format_version: "3.0"
_transform: true

services:
  - name: payment-service
    protocol: "http"
    host: payment-api
    port: 8081

routes:
  - name: config
    hosts:
      - "*"
    strip_path: false
    paths:
      - "/config"
    methods:
      - POST
      - GET
      - PUT
      - DELETE

plugins:
  - name: cors
    config:
      allow_origin: ["*"]
