_format_version: "3.0"

services:
  - name: payment-service
    url: http://localhost:8081

routes:
  - name: payments
    hosts:
      - "*"
    paths:
      - "/payments"
    methods:
      - POST
      - GET
      - PUT
      - DELETE

plugins:
  - name: cors
    config:
      allow_origin: ["*"]
