version: "3"
services:
  queue-control:
    image: rabbitmq:3-management-alpine
  frontend:
    image: gastrocontrol/web
    container_name: "web"
    build:
      context: web
    ports:
      - 3000:3000

networks:
  kong-net:
    name: "kong-net"
    driver: "bridge"
