version: "3"
services:
  queue-control:
    image: rabbitmq:3-management-alpine

  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    depends_on:
      - kong-database
    networks:
      - core

  kong-database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    networks:
      - core

  core:
    container_name: "core"
    build:
      context: .
      dockerfile: ./core

  web:
    container_name: "web"
    build:
      context: ./web
networks:
  core:
    name: "core"
